set default highspeed_parts to "EmptyPart"
This is needed because `std::to_array<std::string_view>` doesn't work on
empty array.

```
Step #1: | include/estoraged_conf.hpp:10:36: error: no matching function for call to 'to_array<std::string_view>(<brace-enclosed initializer list>)'
Step #1: |    10 |     std::to_array<std::string_view>({  });
```

Change-Id: I98115aa1a16cb35d5d67c5886651a5261abeea78
Signed-off-by: Willy Tu <wltu@google.com>